#!/usr/bin/env php
<?php
/**
 * Created by PhpStorm.
 * User: Sofiane Akbly <sofiane.akbly@gmail.com>
 * Date: 27/07/2021
 * Time: 11:25
 */

use Sofiakb\Database\NoSQL\Console\Commands\Command;

require 'vendor/autoload.php';

try {
    if ($argc > 1) {
        
        $commands = Command::getCommands();
        
        $command = $argv[1];
        
        if (isset($commands[$command])) {
            $class = $commands[$command];
            $object = new $class($argv);
            exit($object->handle());
        } else {
            throw new Exception("Command [$command] not found");
        }
    }
} catch (Throwable $e) {
    echo PHP_EOL . "\033[01;33m" . $e->getFile() . "(" . $e->getLine() . ") : \033[0m" . PHP_EOL . PHP_EOL;
    echo "\033[01;31m" . $e->getMessage() . "\033[0m" . PHP_EOL . PHP_EOL;
    exit(1);
}
